# netlify.toml

[build]
  # Install Hugo first before building the site
  command = "npm install -g hugo && hugo"
  
  # The directory where the built site will be stored
  publish = "public"

[build.environment]
  # Specify the Hugo version if needed
  HUGO_VERSION = "0.88.1"

[context.production.environment]
  # Example: Set other environment variables for production if needed
  HUGO_ENV = "production"
  
[context.deploy-preview.environment]
  # Set up environment variables for deploy preview if needed
  HUGO_ENV = "preview"
